#!/bin/bash
# Upload to Google Drive using rclone - Setup Instructions

echo "=== Google Drive Upload Setup ==="
echo ""
echo "Step 1: Configure rclone for Google Drive"
echo "Run: rclone config"
echo ""
echo "Follow these steps in the configuration:"
echo "1. Choose 'n' for new remote"
echo "2. Enter name: gdrive"
echo "3. Choose storage type: drive (Google Drive)"
echo "4. Leave client_id and client_secret blank (press Enter)"
echo "5. Choose scope: 1 (Full access)"
echo "6. Leave root_folder_id blank"
echo "7. Leave service_account_file blank"
echo "8. Choose 'n' for advanced config"
echo "9. Choose 'y' for auto config (this will open a browser)"
echo "10. Complete the Google authentication in the browser"
echo "11. Choose 'n' for team drive"
echo "12. Choose 'y' to confirm"
echo ""
echo "Step 2: Upload your PDF"
echo "Run: rclone copy merged_document.pdf gdrive:"
echo ""
echo "Or use this script after configuration is complete!"
